project:
  type: website

website:
  title: "Posit Team User Training"
  favicon: images/favicon.svg
  navbar: 
    pinned: true
        
format:
  html:
    theme: cosmo
    css: styles.css

editor: source

